baseurl = "ikellog.github.io" # Hostname (and path) to the root.
title = "James Le Nguyen" # Site title.
theme = "hugo-coder-portfolio-master" # Set the theme.
languagecode = "en-us" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en-us" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = false # Enable or disable Disqus.

[params] # theme parameters
    author = "James Le Nguyen" # Author's name.
    info = "Salesforce Admin / Developer" # Author's job title or info.
    description = "James Le Nguyen's personal website" # Site description.
    keywords = "blog,admin, developer,personal" # Site keywords.
    avatarurl = "images/avatarj.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = false # Add footer content
    fixedbarContent = false # Add fixedbar content
    fixedbarContentAfter = false # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ikellog"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/beingoffline"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/jlenguyen/"
[[params.social]]
    # If icon is not set, Text is displayed.
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/jlenguyen/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "projects"